package com.pregnantunicorn.goldentitty.models.current_fragment

enum class FragmentType {

    LOCATION_FRAGMENT,
    ENTRANCE_FRAGMENT,
    ACTION_FRAGMENT,
    SNEAK_FRAGMENT,
    PALM_FRAGMENT,
    CAFETERIA_FRAGMENT,
    SLEEPING_BAG_FRAGMENT,
    CONSTRUCTION_FRAGMENT,
    WORKSHOP_FRAGMENT,
    FISHING_SPOT_FRAGMENT,
    CAMP_FIRE_FRAGMENT,
    EXCAVATION_FRAGMENT,
    BATTLEFIELD_FRAGMENT,
    TEMPLE_FRAGMENT,
    CHIDINMA_STATUE_FRAGMENT,
    INFORMATION_FRAGMENT,
    GOLDEN_TITTY_FRAGMENT
}