package com.pregnantunicorn.goldentitty.models.story_line

enum class EventTitle {

    LADY_SILVIAS_DEATH,
    OPENING,
    ENDING,
    WORKSHOP_EVENT,
    EXCAVATION_SITE_EVENT,
    CAMP_FIRE_EVENT,
    FIRST_FLOOR_OPENING_EVENT,
    FIRST_FLOOR_DEATH_EVENT,
    FIRST_FLOOR_ENDING_EVENT,
    SECOND_FLOOR_OPENING_EVENT,
    SECOND_FLOOR_DEATH_EVENT,
    SECOND_FLOOR_ENDING_EVENT,
    THIRD_FLOOR_OPENING_EVENT,
    THIRD_FLOOR_DEATH_EVENT,
    THIRD_FLOOR_ENDING_EVENT,
    TEAMS_DEATH,
    LADY_SILVIAS_HUT_EVENT,
    STATUE_EVENT,
    TEMPLE_EVENT,
    METEORS_DEATH,
    PIER_EVENT,
    WESTERN_GATE

}
