package com.pregnantunicorn.merchantofgoldlakehorizon.models.current_fragment

enum class FragmentType {

    LOCATION_FRAGMENT,
    ENTRANCE_FRAGMENT,
    ACTION_FRAGMENT,
    SNEAK_FRAGMENT,
    PEARL_TITTY_FRAGMENT,
    PALM_FRAGMENT,
    CAFETERIA_FRAGMENT,
    UNIVERSITY_FRAGMENT,
    BOOMERANG_SHOP_FRAGMENT,
    SLEEPING_BAG_FRAGMENT,
    CARRIAGE_FRAGMENT,
    TEMPLE_FRAGMENT

}